import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'es' | 'en';

type LanguageContextType = {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
};

const translations = {
  en: {
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.team': 'Team',
    'nav.vehicles': 'Vehicles',
    'nav.partners': 'Partners',
    'nav.contact': 'Contact',
    'nav.join': 'Join Us',
    'hero.title': 'Racing Towards a Sustainable Future',
    'hero.tagline': 'The solar racing team of Universitat Politècnica de València',
    'hero.subtitle': 'Driving the next generation of solar-powered mobility with a commitment to sustainable innovation and cutting-edge technology.',
    'hero.learnMore': 'Learn More',
    'hero.joinTeam': 'Join the Team',
    'countdown.title': 'Time Until Race Day',
    'countdown.days': 'Days',
    'countdown.hours': 'Hours',
    'countdown.minutes': 'Minutes',
    'countdown.seconds': 'Seconds',
    'home.title': 'The Future of Solar Mobility',
    'home.subtitle': 'Leading the way towards <span class="text-yellow-300 font-semibold">renewable energies</span> through <span class="text-yellow-300 font-semibold">innovation</span> and <br><span class="text-yellow-300 font-semibold">education</span>, aimed at building a clean and efficient future.',
    'home.stats.engineers': 'Engineers',
    'home.stats.prototypes': 'Prototypes',
    'home.stats.years': 'Years',
    'home.stats.mission': 'Mission',
    'home.team.title': 'Driven by passion, built by engineers',
    'home.team.description': 'We are a multidisciplinary team of students from UPV united by one goal: to push the limits of solar mobility. From aerodynamics to electronics, every member brings their expertise to build something extraordinary.',
    'home.team.cta': 'Meet the team',
    'home.partners.label': 'Trusted by our partners',
    'home.features.innovation.title': 'Innovation',
    'home.features.innovation.description': 'We explore new frontiers in aerodynamics, energy efficiency, and solar mobility. Using cutting-edge technologies, we optimize performance and build a future towards renewable energies.',
    'home.features.sustainability.title': 'Sustainability',
    'home.features.sustainability.description': 'Sustainability is at the heart of our mission. Through advanced research in renewable energy, we aim to create eco-friendly transport solutions that contribute to an efficient and responsible future.',
    'home.features.education.title': 'Education',
    'home.features.education.description': 'Our team promotes knowledge-sharing and hands-on experience, empowering the next generation of engineers. We offer real-world challenges that enhance technical skills and drive future innovation in sustainable mobility.',
    'about.title': 'About HeliosRace UPV',
    'about.subtitle': 'From the land of the sun, towards the future of mobility.',
    'about.mission.title': 'Our Mission',
    'about.mission.text1': 'At Helios Race UPV we are a team of engineering students united by a common goal: to redefine the limits of energy efficiency. We design and build high-performance solar electric vehicles to compete at an international level and prove that sustainable innovation is not the future — it is the present.',
    'about.vision.title': 'Vision',
    'about.vision.text': 'To become an international benchmark in engineering applied to sustainable mobility. We aspire to lead the development of solar vehicles, demonstrating the potential of clean energy and bringing tomorrow\'s technology closer to today\'s society.',
    'about.values.title': 'Values',
    'about.values.innovation': 'Innovation',
    'about.values.innovation.text': 'We constantly seek new ways to improve. We challenge the status quo, experiment, and evolve.',
    'about.values.sustainability': 'Sustainability',
    'about.values.sustainability.text': 'We design with impact in mind. We pursue efficient, responsible solutions aligned with the future of the planet.',
    'about.values.teamwork': 'Teamwork',
    'about.values.teamwork.text': 'Talent adds up, but the team multiplies. We grow together through collaboration, respect, and communication.',
    'about.values.commitment': 'Commitment',
    'about.values.commitment.text': 'We give our best in every challenge. Passion and discipline are the engine behind each of our projects.',
    'about.competition.title': 'Competition',
    'about.competition.text': 'The ILumen European Solar Challenge (IESC) seeks the development of vehicle propulsion technology through solar energy, through friendly competition among participating teams. On August 22 and 23, 2024, the HeliosRace UPV team had the pleasure and opportunity to participate with their first prototype at the Zolder circuit in Heusden-Zolder, Belgium.',
    'about.vehicles.title': 'Meet Our Vehicles',
    'about.vehicles.prototype1': 'Our first prototype. The beginning of a legacy.',
    'about.vehicles.prototype2': 'Our second bet. The future of Helios Race UPV.',
    'about.findUs.title': 'Find Us',
    'team.title': 'Meet Our Team',
    'team.subtitle': 'Students working together to push the boundaries of solar racing and develop a future based on the sustainable mobility.',
    'team.description': 'Our team consists of passionate students from various engineering disciplines, working together to create innovative solar-powered racing solutions. Each member brings unique skills and perspectives to the project.',
    'team.departments': 'Departments',
    'team.department': 'Department',
    'team.comingSoon': 'Coming soon...',
    'team.season': 'Team',
    'team.dept.direccion': 'Management',
    'team.dept.mecanica': 'Mechanics',
    'team.dept.estructura': 'Structure',
    'team.dept.electronica': 'Electronics',
    'team.dept.baterias': 'Batteries',
    'team.dept.fotovoltaica': 'Photovoltaic',
    'team.dept.telemetria': 'Telemetry',
    'team.dept.motor': 'Motor',
    'team.dept.iluminacion': 'Lighting',
    'team.dept.marketing': 'Marketing & Design',
    'team.dept.partners': 'Partners & Finance',
    'partners.title': 'Our Partners',
    'partners.subtitle': 'Collaboration is key to our success. Meet the organizations that support our mission.',
    'partners.becomePartner.title': 'Become a Partner',
    'partners.becomePartner.text': 'Join us in our mission to advance sustainable transportation technology. Partner with HeliosRace UPV and be part of the future of solar movility.',
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Have questions or want to learn more about HeliosRace UPV? Get in touch with us.',
    'contact.nameLabel': 'Name',
    'contact.namePlaceholder': 'Your name',
    'contact.emailLabel': 'Email',
    'contact.emailPlaceholder': 'your.email@example.com',
    'contact.messageLabel': 'Message',
    'contact.messagePlaceholder': 'Your message...',
    'contact.submitButton': 'Send Message',
    'contact.sendingButton': 'Sending...',
    'contact.successTitle': 'Message Sent!',
    'contact.successDescription': 'We will get back to you as soon as possible.',
    'contact.errorTitle': 'Error',
    'contact.errorDescription': 'There was a problem sending your message. Please try again later.',
    'join.title': 'Join Our Team',
    'join.subtitle': 'Be part of the future of sustainable racing technology',
    'join.readyTitle': 'Ready to Join?',
    'join.readyText': 'Apply now through our application form. We\'re looking forward to meeting you!',
    'join.apply': 'Apply Now',
    'join.titlend': 'Do you want to join?',
    'join.description': 'If you are passionate about technology, innovation and motorsports, join us! Work with us closely to develop a sustainable and efficient propulsion system. We are waiting for you!',
    'join.button': 'Apply Now',
    'vehicles.title': 'Our Vehicles',
    'vehicles.prototype1.title': 'Prototype 1',
    'vehicles.prototype1.description1': 'Our first solar vehicle was designed to maximize efficiency and aerodynamics. It features an ultra-light chassis and high-performance photovoltaic cells, allowing for outstanding energy optimization.',
    'vehicles.prototype1.description2': 'With exceptional autonomy and innovative materials, Prototype 1 marked a milestone in our history by competing in prestigious international events.',
    'vehicles.prototype2.title': 'Prototype 2',
    'vehicles.prototype2.description1': 'With a focus on innovation and sustainability, Prototype 2 incorporates improvements in aerodynamics and a more efficient energy management system. Thanks to its optimized design, this model exceeds performance standards in solar competitions.',
    'vehicles.prototype2.description2': 'From its conception, this prototype has been designed to maximize speed and autonomy, reducing environmental impact and promoting sustainable mobility.',
    'vehicles.learnMore': 'Learn more →',
    'vehicles1.prototype1.title': 'Prototype 1',
    'vehicles1.prototype1.subtitle': 'Our first prototype. The beginning of a legacy.',
    'vehicles1.prototype1.design.title': 'Design and Aerodynamics',
    'vehicles1.prototype1.design.description': 'Prototype 1 was designed with a focus on aerodynamic efficiency, reducing wind resistance and maximizing solar energy utilization.',
    'vehicles1.prototype1.design.alt': 'Prototype 1 - Side view',
    'vehicles1.prototype1.components.title': 'Innovative Components',
    'vehicles1.prototype1.components.description': 'Equipped with next-generation batteries and an intelligent monitoring system, the vehicle optimizes its performance in real-time, ensuring superior efficiency in every competition.',
    'vehicles1.prototype1.components.alt': 'Prototype 1 - Interior',
    'vehicles1.prototype1.achievements.title': 'Competition Achievements',
    'vehicles1.prototype1.achievements.description': 'Thanks to its innovative design, Prototype 1 successfully participated in multiple competitions, demonstrating the potential of solar energy in transportation and achieving excellent results.',
    'vehicles1.prototype1.achievements.alt': 'Prototype 1 - Competition',
    'vehicles2.prototype2.title': 'Prototype 2',
    'vehicles2.prototype2.subtitle': 'Our second bet. The future of Helios Race UPV.',
    'vehicles2.prototype2.design.title': 'Design and Aerodynamics',
    'vehicles2.prototype2.design.description': 'Prototype 2 was designed with a focus on aerodynamic efficiency, reducing wind resistance and maximizing solar energy utilization.',
    'vehicles2.prototype2.design.alt': 'Prototype 2 - Side view',
    'vehicles2.prototype2.components.title': 'Innovative Components',
    'vehicles2.prototype2.components.description': 'Equipped with next-generation batteries and an intelligent monitoring system, the vehicle optimizes its performance in real-time, ensuring superior efficiency in every competition.',
    'vehicles2.prototype2.components.alt': 'Prototype 2 - Interior',
    'vehicles2.prototype2.achievements.title': 'Competition Achievements',
    'vehicles2.prototype2.achievements.description': 'Thanks to its innovative design, Prototype 2 successfully participated in multiple competitions, demonstrating the potential of solar energy in transportation and achieving excellent results.',
    'vehicles2.prototype2.achievements.alt': 'Prototype 2 - Competition',
    'vehicles.back': 'Back to Vehicles',
  },
  es: {
    'nav.home': 'Inicio',
    'nav.about': 'Acerca',
    'nav.team': 'Equipo',
    'nav.vehicles': 'Vehículos',
    'nav.partners': 'Partners',
    'nav.contact': 'Contacto',
    'nav.join': 'Únete',
    'hero.title': 'Acelerando Hacia un Futuro Sostenible',
    'hero.tagline': 'El equipo de carreras solares de la Universitat Politècnica de València',
    'hero.subtitle': 'Impulsando la próxima generación de movilidad solar con un compromiso con la innovación sostenible y tecnología de vanguardia.',
    'hero.learnMore': 'Conoce Más',
    'hero.joinTeam': 'Únete al Equipo',
    'countdown.title': 'Tiempo Hasta la Carrera',
    'countdown.days': 'Días',
    'countdown.hours': 'Horas',
    'countdown.minutes': 'Minutos',
    'countdown.seconds': 'Segundos',
    'home.title': 'El Futuro de la Movilidad Solar',
    'home.subtitle': 'Liderando el camino hacia las <span class="text-yellow-300 font-semibold">energías renovables</span> a través de la <span class="text-yellow-300 font-semibold">innovación</span> y <span class="text-yellow-300 font-semibold">educación</span>, orientadas a construir un futuro limpio y eficiente.',
    'home.stats.engineers': 'Ingenieros',
    'home.stats.prototypes': 'Prototipos',
    'home.stats.years': 'Años',
    'home.stats.mission': 'Misión',
    'home.team.title': 'Movidos por la pasión, construidos por ingenieros',
    'home.team.description': 'Somos un equipo multidisciplinar de estudiantes de la UPV unidos por un objetivo: llevar la movilidad solar al límite. Desde aerodinámica hasta electrónica, cada miembro aporta su especialidad para construir algo extraordinario.',
    'home.team.cta': 'Conoce al equipo',
    'home.partners.label': 'Con el apoyo de nuestros partners',
    'home.features.innovation.title': 'Innovación',
    'home.features.innovation.description': 'Exploramos nuevas fronteras en aerodinámica, eficiencia energética y movilidad solar. Utilizando tecnologías de vanguardia, optimizamos el rendimiento y construimos un futuro hacia la movilidad sostenible.',
    'home.features.sustainability.title': 'Sostenibilidad',
    'home.features.sustainability.description': 'La sostenibilidad es el corazón de nuestra misión. A través de la investigación avanzada en energías renovables, buscamos crear soluciones de transporte ecológicas que contribuyan a un futuro eficiente y responsable.',
    'home.features.education.title': 'Educación',
    'home.features.education.description': 'Nuestro equipo promueve el intercambio de conocimientos y la experiencia práctica, ofreciendo desafíos del mundo real que mejoran las habilidades técnicas y fomentan la innovación futura.',
    'about.title': 'Sobre Helios Race UPV',
    'about.subtitle': 'Desde la tierra del sol hacia el futuro de la movilidad.',
    'about.mission.title': 'Nuestra Misión',
    'about.mission.text1': 'En Helios Race UPV somos un equipo de estudiantes de ingeniería unidos por un objetivo común: redefinir los límites de la eficiencia energética. Diseñamos y construimos vehículos eléctricos solares de alto rendimiento para competir a nivel internacional y demostrar que la innovación sostenible no es el futuro, es el presente.',
    'about.vision.title': 'Visión',
    'about.vision.text': 'Convertirnos en un referente internacional en ingeniería aplicada a la movilidad sostenible. Aspiramos a liderar el desarrollo de vehículos solares, demostrando el potencial de la energía limpia y acercando la tecnología del futuro a la sociedad actual.',
    'about.values.title': 'Valores',
    'about.values.innovation': 'Innovación',
    'about.values.innovation.text': 'Buscamos constantemente nuevas formas de mejorar. Cuestionamos lo establecido, experimentamos y evolucionamos.',
    'about.values.sustainability': 'Sostenibilidad',
    'about.values.sustainability.text': 'Diseñamos pensando en el impacto. Apostamos por soluciones eficientes, responsables y alineadas con el futuro del planeta.',
    'about.values.teamwork': 'Trabajo en equipo',
    'about.values.teamwork.text': 'El talento suma, pero el equipo multiplica. Crecemos juntos a través de la colaboración, el respeto y la comunicación.',
    'about.values.commitment': 'Compromiso',
    'about.values.commitment.text': 'Nos implicamos al máximo en cada reto. La pasión y la disciplina son el motor que impulsa cada uno de nuestros proyectos.',
    'about.competition.title': 'Competición',
    'about.competition.text': 'La ILumen European Solar Challenge (IESC) busca el desarrollo de la tecnología de propulsión de vehículos por medio de energía de procedencia solar, mediante la competitividad amistosa entre los equipos participantes. Durante los días 22 y 23 de agosto de 2024, el equipo de HeliosRace UPV tuvo el placer y oportunidad de participar junto a su primer prototipo en el circuito Zolder en Heusden-Zolder, Bélgica.',
    'about.vehicles.title': 'Conoce nuestros vehículos',
    'vehicles.prototype1.title': 'Prototipo 1',
    'about.vehicles.prototype1': 'Nuestro primer prototipo. El comienzo de un legado.',
    'about.vehicles.prototype2': 'Nuestra segunda apuesta. El futuro de Helios Race UPV.',
    'about.findUs.title': 'Encuéntranos',
    'team.title': 'Conoce a Nuestro Equipo',
    'team.subtitle': 'Estudiantes trabajando juntos para impulsar los límites de las carreras solares y desarrollar un futuro basado en la movilidad sostenible.',
    'team.description': 'Nuestro equipo está formado por estudiantes apasionados de varias disciplinas de ingeniería, trabajando juntos para crear soluciones innovadoras de carreras solares. Cada miembro aporta habilidades y perspectivas únicas al proyecto.',
    'team.departments': 'Departamentos',
    'team.department': 'Departamento',
    'team.comingSoon': 'Próximamente...',
    'team.season': 'Equipo',
    'team.dept.direccion': 'Dirección',
    'team.dept.mecanica': 'Mecánica',
    'team.dept.estructura': 'Estructura',
    'team.dept.electronica': 'Electrónica',
    'team.dept.baterias': 'Baterías',
    'team.dept.fotovoltaica': 'Fotovoltaica',
    'team.dept.telemetria': 'Telemetría',
    'team.dept.motor': 'Motor',
    'team.dept.iluminacion': 'Iluminación',
    'team.dept.marketing': 'Marketing y Diseño',
    'team.dept.partners': 'Partners y Finanzas',
    'partners.title': 'Nuestros Partners',
    'partners.subtitle': 'La colaboración es clave para nuestro éxito. Conoce a las organizaciones que apoyan nuestra misión.',
    'partners.becomePartner.title': 'Conviértete en Partner',
    'partners.becomePartner.text': 'Únete a nuestra misión de avanzar en la tecnología de transporte sostenible. Colabora con HeliosRace UPV y sé parte del futuro de la movilidad solar.',
    'contact.title': 'Contáctanos',
    'contact.subtitle': '¿Tienes preguntas o quieres saber más sobre HeliosRace UPV? Ponte en contacto con nosotros.',
    'contact.nameLabel': 'Nombre',
    'contact.namePlaceholder': 'Tu nombre',
    'contact.emailLabel': 'Email',
    'contact.emailPlaceholder': 'tu.email@ejemplo.com',
    'contact.messageLabel': 'Mensaje',
    'contact.messagePlaceholder': 'Tu mensaje...',
    'contact.submitButton': 'Enviar mensaje',
    'contact.sendingButton': 'Enviando...',
    'contact.successTitle': '¡Mensaje enviado!',
    'contact.successDescription': 'Nos pondremos en contacto contigo lo antes posible.',
    'contact.errorTitle': 'Error',
    'contact.errorDescription': 'Hubo un problema al enviar tu mensaje. Por favor, inténtalo de nuevo más tarde.',
    'join.title': 'Únete a Nuestro Equipo',
    'join.subtitle': 'Sé parte del futuro de la tecnología de carreras sostenibles',
    'join.readyTitle': '¿Listo para Unirte?',
    'join.readyText': 'Aplica ahora a través de nuestro formulario. ¡Esperamos conocerte!',
    'join.apply': 'Aplicar Ahora',
    'join.titlend': '¿Quieres unirte?',
    'join.description': 'Si te apasiona la tecnología, la innovación y el automovilismo, ¡únete! Trabaja con nosotros de cerca para desarrollar un sistema de propulsión sostenible y eficiente. ¡Te esperamos!',
    'join.button': 'Apúntate',
    'vehicles.title': 'Nuestros Vehículos',
    'vehicles.prototype1.description1': 'El primero de todos. Cuenta con un chasis ligero y un motor eléctrico de alto rendimiento.',
    'vehicles.prototype1.description2': 'Con una autonomía excepcional y materiales innovadores, el Prototipo 1 marcó un hito en nuestra historia al competir en prestigiosos eventos internacionales.',
    'vehicles.prototype2.title': 'Prototipo 2',
    'vehicles.prototype2.description1': 'Nuestra próxima creación. Apostamos por un vehículo mejorado en términos de eficiencia, sensorización y aerodinámica gracias a la experiencia obtenida.',
    'vehicles.prototype2.description2': 'Desde su concepción, este prototipo ha sido diseñado para maximizar la velocidad y autonomía, reduciendo el impacto ambiental y promoviendo una movilidad sostenible.',
    'vehicles.learnMore': 'Conocer más →',
    'vehicles1.prototype1.title': 'Prototipo 1',
    'vehicles1.prototype1.subtitle': 'Nuestro primer prototipo. El comienzo de un legado.',
    'vehicles1.prototype1.design.title': 'Diseño y Aerodinámica',
    'vehicles1.prototype1.design.description': 'El Prototipo 1 fue diseñado con un enfoque en la eficiencia aerodinámica, reduciendo la resistencia al viento y maximizando el aprovechamiento de la energía solar.',
    'vehicles1.prototype1.design.alt': 'Prototipo 1 - Vista lateral',
    'vehicles1.prototype1.components.title': 'Componentes Innovadores',
    'vehicles1.prototype1.components.description': 'Equipado con baterías de última generación y un sistema de monitoreo inteligente, el vehículo optimiza su rendimiento en tiempo real, asegurando una eficiencia superior en cada competencia.',
    'vehicles1.prototype1.components.alt': 'Prototipo 1 - Interior',
    'vehicles1.prototype1.achievements.title': 'Logros en Competencias',
    'vehicles1.prototype1.achievements.description': 'Gracias a su diseño innovador, el Prototipo 1 participó con éxito en múltiples competiciones, demostrando el potencial de la energía solar en el transporte y alcanzando excelentes resultados.',
    'vehicles1.prototype1.achievements.alt': 'Prototipo 1 - Competencia',
    'vehicles2.prototype2.title': 'Prototipo 2',
    'vehicles2.prototype2.subtitle': 'Nuestra segunda apuesta. El futuro de Helios Race UPV.',
    'vehicles2.prototype2.design.title': 'Diseño y Aerodinámica',
    'vehicles2.prototype2.design.description': 'El Prototipo 2 fue diseñado con un enfoque en la eficiencia aerodinámica, reduciendo la resistencia al viento y maximizando el aprovechamiento de la energía solar.',
    'vehicles2.prototype2.design.alt': 'Prototipo 2 - Vista lateral',
    'vehicles2.prototype2.components.title': 'Componentes Innovadores',
    'vehicles2.prototype2.components.description': 'Equipado con baterías de última generación y un sistema de monitoreo inteligente, el vehículo optimiza su rendimiento en tiempo real, asegurando una eficiencia superior en cada competencia.',
    'vehicles2.prototype2.components.alt': 'Prototipo 2 - Interior',
    'vehicles2.prototype2.achievements.title': 'Logros en Competencias',
    'vehicles2.prototype2.achievements.description': 'Gracias a su diseño innovador, el Prototipo 2 participó con éxito en múltiples competiciones, demostrando el potencial de la energía solar en el transporte y alcanzando excelentes resultados.',
    'vehicles2.prototype2.achievements.alt': 'Prototipo 2 - Competencia',
    'vehicles.back': 'Volver a Vehículos',
  },
} as const;

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('es');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}